## LDAP
cas.authn.ldap[0].name=ICIQ LDAP
cas.authn.ldap[0].ldapUrl=ldap://iciqdc01.iciq.es:389/
cas.authn.ldap[0].baseDn=CN=users,dc=ICIQ,dc=ES
cas.authn.ldap[0].bindDn=CN=ldapechempad,CN=users,dc=ICIQ,dc=ES

# Search criteria
cas.authn.ldap[0].searchFilter=(userPrincipalName={user})

# Connection
cas.authn.ldap[0].minPoolSize=3
cas.authn.ldap[0].maxPoolSize=10

# Auth type
cas.authn.ldap[0].type=AUTHENTICATED

cas.authn.ldap[0].bind-credential=${LDAP_TOKEN}

# Disables pooling, so we do not fail at start if the DNS of the ICIQ LDAP server is not resolvable
cas.authn.ldap[0].disable-pooling=true