name: ci

# Trigger event on every push / delete event, no matter the branch
# on: [push, delete]

# Trigger event on every push / delete event, only in master branch
on:
  push:
    branches:
      - "master"
  delete:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/echempad-cas:latest

  mirror:
    needs: build
    runs-on: ubuntu-latest
    steps: # <-- must use actions/checkout before mirroring!
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: checkoutLFS
        uses: actions/checkout@v2                       # <-- Do checkout of LFS elements
      - run: git lfs fetch --all
      - run: git lfs pull
      - run: git lfs pull origin
      - run: git fetch --unshallow
      - run: mkdir -p ~/.ssh
      - run: touch ~/.ssh/config
      - run: echo 'Host *' | tee -a ~/.ssh/config
      - run: echo 'ServerAliveInterval 30' | tee -a ~/.ssh/config
      - run: echo 'ServerAliveCountMax 1200' | tee -a ~/.ssh/config
      - run: echo 'TCPKeepAlive yes' | tee -a ~/.ssh/config
      - run: git lfs fetch --all
      - run: git lfs pull
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:ICIQ-DMP/eChempad-CAS-public-mirror
          ssh_private_key: # <-- use 'secrets' to pass credential information.
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}       # <-- the corresponding public key is also stored in github, not only gitlab, so they can use the same private token


  deploy:
    needs: mirror
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download docker-compose.yml
        run: mv docker-compose.ci.yml docker-compose.yml

      - name: Stop eChempad cas container
        run: docker-compose down

      - name: Force pulling of the images or they would not be updated
        run: docker-compose pull

      - name: restart eChempad cas container with new image
        run: docker-compose up -d